# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 951750bb210eb9e38283b0b41795fa05559d962d37b8ce3a538c893c8d4bbf1619b88191db1bbf163e564afec2321f12e6f78d88e38eee4b18a33a71fbfc9fc9

test:
  secret_key_base: 0db348bb147886fa98d7ca65ba25180036c77d979f61fb9eaa1cbca4878190575686e5152186a9302aa5c368d4f3c32933b77c6822b1b50b4122f38738c7c9e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
